# Generated by Django 3.1.4 on 2020-12-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20201225_1955"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="UserInterest",
            new_name="UseInterest",
        ),
    ]
