# Generated by Django 3.1.4 on 2021-05-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_emailactivation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailactivation',
            name='expires',
            field=models.IntegerField(default=2),
        ),
    ]
