# Generated by Django 3.1.4 on 2021-05-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantATreeKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=8, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('LOT', models.CharField(max_length=5)),
                ('GTIN', models.CharField(max_length=14)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
